/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IIUC;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Tahsin Abrar
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        colr();
    }
    void colr()
    {
       Color c = new Color(0,63,80);
       loading.setBackground(c);
    }
     public static void loding()
    {
        Start n = new Start();
        n.setVisible(true);
        
        try
        {
            for(int i=0; i<=100; i++)
            {
                Thread.sleep(50);
                n.loadingValue1.setText(i+" %");
            if (i == 10)
                n.jLabel3.setText("Turning On Modules . . .");
            
            if (i == 20)
                n.jLabel3.setText("Loading Modules . . .");
            
            if (i == 40)
                n.jLabel3.setText("Connection to Databace . . .");
            
            if (i == 60)
                n.jLabel3.setText("Connection Successful . . .");
            
            if (i == 90)
                n.jLabel3.setText("Launching Application . . .");
            n.loading.setValue(i);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        Welcome a = new Welcome();
        n.setVisible(false);
        a.setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loading = new javax.swing.JProgressBar();
        loadingValue1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loading.setBackground(new java.awt.Color(0, 63, 80));
        loading.setForeground(new java.awt.Color(0, 122, 155));
        getContentPane().add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 583, 950, 17));

        loadingValue1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingValue1.setForeground(new java.awt.Color(255, 255, 255));
        loadingValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingValue1.setText("0 %");
        getContentPane().add(loadingValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Loading ...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GIF/Smoke_00000.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));

        setSize(new java.awt.Dimension(950, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        loding();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar loading;
    private javax.swing.JLabel loadingValue1;
    // End of variables declaration//GEN-END:variables
}
